create table if not exists candidatos_senador (
  id uuid primary key default gen_random_uuid(),
  ano_eleicao int not null,
  uf text not null,
  nr_candidato text,
  sq_candidato text not null unique,
  id_externo_api text,
  nome_urna text,
  nome_completo text,
  slug text unique,
  partido_sigla text,
  partido_numero text,
  partido_nome text,
  coligacao_nome text,
  coligacao_composicao text,
  situacao_candidatura text,
  reeleicao boolean,
  data_nascimento date,
  naturalidade_uf text,
  genero text,
  grau_instrucao text,
  estado_civil text,
  cor_raca text,
  ocupacao text,
  foto_url text,
  fonte_api text default 'divulgacandcontas',
  agente_id uuid references agentes_politicos(id) on delete set null,
  suplentes jsonb,
  situacao_tse text,
  apto_tse boolean,
  consta_da_urna text,
  totalizacao_tse text,
  numero_processo text,
  motivos jsonb,
  substituido boolean,
  substituto_sq text,
  substituto_nome text,
  municipio_nascimento text,
  nacionalidade text,
  documentos jsonb,
  redes jsonb,
  divulga_bens boolean,
  total_de_bens numeric,
  bens jsonb,
  eleicoes_anteriores jsonb,
  ficha_coletada_em timestamptz,
  ficha_fonte_url text,
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now()
);
create index if not exists idx_cand_senador_uf on candidatos_senador (uf);
create index if not exists idx_cand_senador_agente on candidatos_senador (agente_id);
alter table candidatos_senador enable row level security;
drop policy if exists "Leitura pública" on candidatos_senador;
create policy "Leitura pública" on candidatos_senador for select using (true);
