CREATE TABLE public.agentes_politicos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    nome_completo text NOT NULL,
    nome_urna text,
    partido_atual text,
    cargo_atual text,
    uf_sede character varying(2),
    promessas_campanha jsonb,
    redes_sociais jsonb,
    foto_url text,
    data_atualizacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.analises_politicas (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    titulo text,
    resumo_gemini text,
    auditoria_llama text,
    link_oficial text
);

ALTER TABLE public.analises_politicas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analises_politicas_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.categorias_impacto (
    id integer NOT NULL,
    nome_categoria text,
    palavras_chave text[]
);

CREATE SEQUENCE public.categorias_impacto_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.categorias_impacto_id_seq OWNED BY public.categorias_impacto.id;

CREATE TABLE public.executivo_licitacoes (
    id bigint NOT NULL,
    data_auditoria timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    orgao_nome text, unidade_gestora text, objeto_original text, modalidade text,
    valor_estimado numeric(15,2), resumo_cidadao text, fidelidade_nota integer,
    alerta_auditoria text, link_fonte text, agente_responsavel_id uuid,
    categoria_gasto text, agente_autorizador_id uuid
);

CREATE TABLE public.gastos_cotas_individuais (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    agente_id uuid, ano_mes date, categoria_gasto text, descricao_detalhada text,
    valor_total numeric(15,2), fornecedor_nome text, link_comprovante text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.legislativo_projetos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    titulo_projeto text NOT NULL, link_oficial text NOT NULL, resumo_ia text,
    biblio_transparente jsonb, regua_imparcialidade double precision,
    data_atualizacao timestamp with time zone DEFAULT now(), autor_principal_id uuid
);

CREATE TABLE public.pid2026_judiciario (
    id integer NOT NULL,
    data_processamento timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    data_licitacao date, tribunal character varying(255), objeto_original text,
    resumo_ludico text, nota_transparencia integer, justificativa_auditoria text,
    modalidade character varying(100), link_original text
);

CREATE SEQUENCE public.pid2026_judiciario_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.pid2026_judiciario_id_seq OWNED BY public.pid2026_judiciario.id;

CREATE TABLE public.processos_judiciarios (
    id integer NOT NULL,
    numero_processo character varying(50) NOT NULL,
    tribunal character varying(20) NOT NULL,
    orgao_julgador character varying(255), classe_processual character varying(255),
    resumo_leigo text, analise_tecnica text, assuntos_lista text,
    nota_integridade numeric(3,1), justificativa_auditoria text,
    conflito_identificado boolean DEFAULT false, data_movimentacao_oficial date,
    link_fonte_oficial text,
    criado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    atualizado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    agente_id uuid, politico_envolvido_id uuid
);

CREATE SEQUENCE public.processos_judiciarios_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.processos_judiciarios_id_seq OWNED BY public.processos_judiciarios.id;

CREATE TABLE public.registros_votos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    agente_id uuid, projeto_id uuid, posicao_voto text, data_votacao date,
    ementa_resumida text, alerta_incoerencia boolean DEFAULT false
);

CREATE TABLE public.votos_parlamentares (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    agente_id uuid, projeto_id uuid, voto_tipo text,
    data_voto timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ementa_resumida_voto text
);

ALTER TABLE ONLY public.categorias_impacto ALTER COLUMN id SET DEFAULT nextval('public.categorias_impacto_id_seq'::regclass);
ALTER TABLE ONLY public.pid2026_judiciario ALTER COLUMN id SET DEFAULT nextval('public.pid2026_judiciario_id_seq'::regclass);
ALTER TABLE ONLY public.processos_judiciarios ALTER COLUMN id SET DEFAULT nextval('public.processos_judiciarios_id_seq'::regclass);

ALTER TABLE ONLY public.agentes_politicos ADD CONSTRAINT agentes_politicos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.analises_politicas ADD CONSTRAINT analises_politicas_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.categorias_impacto ADD CONSTRAINT categorias_impacto_nome_categoria_key UNIQUE (nome_categoria);
ALTER TABLE ONLY public.categorias_impacto ADD CONSTRAINT categorias_impacto_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.executivo_licitacoes ADD CONSTRAINT executivo_licitacoes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.gastos_cotas_individuais ADD CONSTRAINT gastos_cotas_individuais_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.legislativo_projetos ADD CONSTRAINT legislativo_projetos_link_oficial_key UNIQUE (link_oficial);
ALTER TABLE ONLY public.legislativo_projetos ADD CONSTRAINT legislativo_projetos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.pid2026_judiciario ADD CONSTRAINT pid2026_judiciario_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.processos_judiciarios ADD CONSTRAINT processos_judiciarios_numero_processo_key UNIQUE (numero_processo);
ALTER TABLE ONLY public.processos_judiciarios ADD CONSTRAINT processos_judiciarios_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.registros_votos ADD CONSTRAINT registros_votos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.agentes_politicos ADD CONSTRAINT unique_nome_urna UNIQUE (nome_urna);
ALTER TABLE ONLY public.votos_parlamentares ADD CONSTRAINT votos_parlamentares_pkey PRIMARY KEY (id);

CREATE INDEX idx_gastos_agente ON public.gastos_cotas_individuais USING btree (agente_id);
CREATE INDEX idx_numero_processo ON public.processos_judiciarios USING btree (numero_processo);
CREATE INDEX idx_votos_agente ON public.registros_votos USING btree (agente_id);

CREATE VIEW public.ranking_gastos_politicos AS
 SELECT ap.nome_urna, ap.partido_atual, gci.categoria_gasto,
    sum(gci.valor_total) AS total_gasto, count(gci.id) AS quantidade_lancamentos
   FROM (public.agentes_politicos ap JOIN public.gastos_cotas_individuais gci ON ((ap.id = gci.agente_id)))
  GROUP BY ap.nome_urna, ap.partido_atual, gci.categoria_gasto
  ORDER BY (sum(gci.valor_total)) DESC;

CREATE VIEW public.resumo_coerencia_votos AS
 SELECT ap.nome_urna, count(rv.id) AS total_votos,
    sum(CASE WHEN rv.alerta_incoerencia THEN 1 ELSE 0 END) AS votos_incoerentes
   FROM (public.agentes_politicos ap JOIN public.registros_votos rv ON ((ap.id = rv.agente_id)))
  GROUP BY ap.nome_urna;

CREATE VIEW public.vista_comparativa_gastos AS
 SELECT categoria_gasto, avg(valor_estimado) AS media_categoria, max(valor_estimado) AS maior_gasto
   FROM public.executivo_licitacoes GROUP BY categoria_gasto;

ALTER TABLE ONLY public.executivo_licitacoes ADD CONSTRAINT executivo_licitacoes_agente_autorizador_id_fkey FOREIGN KEY (agente_autorizador_id) REFERENCES public.agentes_politicos(id);
ALTER TABLE ONLY public.executivo_licitacoes ADD CONSTRAINT executivo_licitacoes_agente_responsavel_id_fkey FOREIGN KEY (agente_responsavel_id) REFERENCES public.agentes_politicos(id);
ALTER TABLE ONLY public.gastos_cotas_individuais ADD CONSTRAINT gastos_cotas_individuais_agente_id_fkey FOREIGN KEY (agente_id) REFERENCES public.agentes_politicos(id);
ALTER TABLE ONLY public.legislativo_projetos ADD CONSTRAINT legislativo_projetos_autor_principal_id_fkey FOREIGN KEY (autor_principal_id) REFERENCES public.agentes_politicos(id);
ALTER TABLE ONLY public.processos_judiciarios ADD CONSTRAINT processos_judiciarios_agente_id_fkey FOREIGN KEY (agente_id) REFERENCES public.agentes_politicos(id);
ALTER TABLE ONLY public.processos_judiciarios ADD CONSTRAINT processos_judiciarios_politico_envolvido_id_fkey FOREIGN KEY (politico_envolvido_id) REFERENCES public.agentes_politicos(id);
ALTER TABLE ONLY public.registros_votos ADD CONSTRAINT registros_votos_agente_id_fkey FOREIGN KEY (agente_id) REFERENCES public.agentes_politicos(id);
ALTER TABLE ONLY public.registros_votos ADD CONSTRAINT registros_votos_projeto_id_fkey FOREIGN KEY (projeto_id) REFERENCES public.legislativo_projetos(id);
ALTER TABLE ONLY public.votos_parlamentares ADD CONSTRAINT votos_parlamentares_agente_id_fkey FOREIGN KEY (agente_id) REFERENCES public.agentes_politicos(id);
ALTER TABLE ONLY public.votos_parlamentares ADD CONSTRAINT votos_parlamentares_projeto_id_fkey FOREIGN KEY (projeto_id) REFERENCES public.legislativo_projetos(id);
